# Default config for Sleeper

# Plugin settings
# The update checker is currently disabled for the Folia branch as it is not the main release
CheckForUpdates: false

# Available serializers:
# minimessage - "<red><bold>Example Text"
FormattingType: "minimessage"

# Main settings
UseAnimation: true
SkipPercentage: 25
SkipSpeed: 100
DelaySleep: false
DelaySeconds: 4
ActionbarMessages: false
PersistentSleepInfo: false
PersistenceTime: 30

# Other settings
BroadcastSleepInfo: false

# Voting system, a night is skipped based on yes votes minus no votes
VoteSkip: false
YesMultiplier: 1
NoMultiplier: 1
SkipVotePercent: 50
BlockBedsAfterVoting: false
BossbarVoteCount: true
ActionbarVoteCount: false
SendVotesOnStart: true
StartWithoutSleep: false
MaxVoteTime: 60
LimitedVoteTime: false

# Plugin integrations
# GSit
GSitPoseToSleep: false
# AFK plugins (AFK+, Essentials)
IgnoreAFKPlayers: true

# General Messages
SleepInfo: "<green>Sleep > <grey>%percent% (%count%) out of a minimum of 25% sleeping."
NightSkip: 
  - "<green>Sleep > <grey>At least 25% of online users sleeping (%count%), skipping the night."
Ignored: "<red>Sleep > <grey>You are still being ignored for sleep calculations!"

# Command messages
SleepHelpList: "<red>Invalid command, valid subcommands are: "
NoPermission: "<red>You don't have permission for that."
PlayerNotFound: "<red>%player% not found."
SelfIgnoreOff: "<green>You are no longer ignored from sleeping."
SelfIgnoreOn: "<red>You are now ignored from sleeping."
OtherIgnoreOff: "<green>%player% is no longer ignored from sleeping."
OtherIgnoreOn: "<red>%player% is now ignored from sleeping."
OtherAlreadyIgnored: "<red>%player% is already ignored from sleeping."
InvalidState: "<red>%input% is not TRUE or FALSE."
ConfigReloaded: "<green>Sleep config reloaded."
OnlyPlayers: "<red>This command can only be run by players."

# Voting Messages
VoteTitle: "<green>Sleep > <grey>Vote below on skipping the night:"
VoteYes: "<green><bold>Yes"
VoteNo: "<red><bold>No"
VotedYes: "<green>You voted to skip the night."
VotedNo: "<green>You voted not to skip the night."
NoVote: "<red>Your world isn't voting on a night skip."
AlreadyYes: "<red>You have already voted yes."
AlreadyNo: "<red>You have already voted no."
VoteNotEnabled: "<red>Voting is not enabled."
ListVotes: "<grey>Votes: <green>Yes: <grey>%yes% <red>No: <grey>%no%"
SkipByVote: "<green>Sleep > <grey>The vote has decided to skip the night!"
VoteTimedOut: "<green>Sleep > <red>The vote ended without skipping the night."
