# Default config for Sleeper

# Plugin settings
CheckForUpdates: true

# Available serializers:
# legacy_ampersand - "&c&lExample Text"
# legacy_section - "§c§lExample Text"
# minimessage - "<red><bold>Example Text"
FormattingType: "legacy_ampersand"

# Main settings
UseAnimation: true
SkipPercentage: 25
SkipSpeed: 100
DelaySleep: false
DelaySeconds: 4

# Other settings
BroadcastNightSkip: false
SendSleepInfo: true
BroadcastSleepInfo: false

# Voting system, a night is skipped based on yes votes minus no votes
VoteSkip: false
YesMultiplier: 1
NoMultiplier: 1
SkipVotePercent: 50
BlockBedsAfterVoting: false
# Available Options: None, BossBar, ActionBar
VoteCountMode: "BossBar"
SendVotesOnStart: true
StartWithoutSleep: false
MaxVoteTime: 60
LimitedVoteTime: false

# General Messages
SleepInfo: "&aSleep > &7%percent% (%count%) out of a minimum of 25% sleeping."
NightSkip: 
  - "&aSleep > &7At least 25% of online users sleeping (%count%), skipping the night."
Ignored: "&cSleep > &7You are still being ignored for sleep calculations!"

# Command messages
SleepHelpList: "&cInvalid command, valid subcommands are: "
NoPermission: "&cYou don't have permission for that."
PlayerNotFound: "&c%player% not found."
SelfIgnoreOff: "&aYou are no longer ignored from sleeping."
SelfIgnoreOn: "&cYou are now ignored from sleeping."
OtherIgnoreOff: "&a%player% is no longer ignored from sleeping."
OtherIgnoreOn: "&c%player% is now ignored from sleeping."
OtherAlreadyIgnored: "&c%player% is already ignored from sleeping."
InvalidState: "&c%input% is not TRUE or FALSE."
ConfigReloaded: "&aSleep config reloaded."
OnlyPlayers: "&cThis command can only be run by players."

# Voting Messages
VoteTitle: "&aSleep > &7Vote below on skipping the night:"
VoteYes: "&a&lYes"
VoteNo: "&c&lNo"
VotedYes: "&aYou voted to skip the night."
VotedNo: "&aYou voted not to skip the night."
NoVote: "&cYour world isn't voting on a night skip."
AlreadyYes: "&cYou have already voted yes."
AlreadyNo: "&cYou have already voted no."
VoteNotEnabled: "&cVoting is not enabled."
ListVotes: "&7Votes: &aYes: &7%yes% &cNo: &7%no%"
SkipByVote: "&aSleep > &7The vote has decided to skip the night!"
VoteTimedOut: "&aSleep > &cThe vote ended without skipping the night."
